# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MenuTabREF.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QGroupBox, QLabel,
    QPushButton, QSizePolicy, QTabWidget, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(535, 665)
        self.gridLayout = QGridLayout(Form)
        self.gridLayout.setObjectName(u"gridLayout")
        self.titleMenuLabel = QLabel(Form)
        self.titleMenuLabel.setObjectName(u"titleMenuLabel")

        self.gridLayout.addWidget(self.titleMenuLabel, 0, 0, 1, 1)

        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabAssetbrowser = QWidget()
        self.tabAssetbrowser.setObjectName(u"tabAssetbrowser")
        self.tabWidget.addTab(self.tabAssetbrowser, "")
        self.tabRetargeting = QWidget()
        self.tabRetargeting.setObjectName(u"tabRetargeting")
        self.tabWidget.addTab(self.tabRetargeting, "")
        self.tabAnimation = QWidget()
        self.tabAnimation.setObjectName(u"tabAnimation")
        self.groupTempCtrls = QGroupBox(self.tabAnimation)
        self.groupTempCtrls.setObjectName(u"groupTempCtrls")
        self.groupTempCtrls.setEnabled(True)
        self.groupTempCtrls.setGeometry(QRect(20, 20, 481, 81))
        self.groupTempCtrls.setAutoFillBackground(False)
        self.groupTempCtrls.setFlat(False)
        self.groupTempCtrls.setCheckable(False)
        self.worldSpaceBtn = QPushButton(self.groupTempCtrls)
        self.worldSpaceBtn.setObjectName(u"worldSpaceBtn")
        self.worldSpaceBtn.setGeometry(QRect(20, 30, 111, 31))
        self.worldSpaceOffsetBtn = QPushButton(self.groupTempCtrls)
        self.worldSpaceOffsetBtn.setObjectName(u"worldSpaceOffsetBtn")
        self.worldSpaceOffsetBtn.setGeometry(QRect(140, 30, 131, 31))
        self.bakeSelectedBtn = QPushButton(self.groupTempCtrls)
        self.bakeSelectedBtn.setObjectName(u"bakeSelectedBtn")
        self.bakeSelectedBtn.setGeometry(QRect(370, 20, 101, 21))
        self.bakeAllBtn = QPushButton(self.groupTempCtrls)
        self.bakeAllBtn.setObjectName(u"bakeAllBtn")
        self.bakeAllBtn.setGeometry(QRect(370, 50, 101, 21))
        self.refreshBtn = QPushButton(self.tabAnimation)
        self.refreshBtn.setObjectName(u"refreshBtn")
        self.refreshBtn.setGeometry(QRect(410, 530, 75, 24))
        self.groupLocatorSettings = QGroupBox(self.tabAnimation)
        self.groupLocatorSettings.setObjectName(u"groupLocatorSettings")
        self.groupLocatorSettings.setGeometry(QRect(20, 509, 351, 51))
        self.locSizeMinBtn = QPushButton(self.groupLocatorSettings)
        self.locSizeMinBtn.setObjectName(u"locSizeMinBtn")
        self.locSizeMinBtn.setGeometry(QRect(10, 20, 61, 24))
        self.locSizeMaxBtn = QPushButton(self.groupLocatorSettings)
        self.locSizeMaxBtn.setObjectName(u"locSizeMaxBtn")
        self.locSizeMaxBtn.setGeometry(QRect(80, 20, 61, 24))
        self.orangeBtn = QPushButton(self.groupLocatorSettings)
        self.orangeBtn.setObjectName(u"orangeBtn")
        self.orangeBtn.setGeometry(QRect(310, 10, 31, 16))
        self.orangeBtn.setStyleSheet(u"background-color: orange;")
        self.orangeBtn.setFlat(False)
        self.redBtn = QPushButton(self.groupLocatorSettings)
        self.redBtn.setObjectName(u"redBtn")
        self.redBtn.setGeometry(QRect(310, 30, 31, 16))
        self.redBtn.setStyleSheet(u"background-color: red;")
        self.redBtn.setFlat(False)
        self.yellowBtn = QPushButton(self.groupLocatorSettings)
        self.yellowBtn.setObjectName(u"yellowBtn")
        self.yellowBtn.setGeometry(QRect(270, 10, 31, 16))
        self.yellowBtn.setStyleSheet(u"background-color: yellow\n"
";")
        self.yellowBtn.setFlat(False)
        self.greenBtn = QPushButton(self.groupLocatorSettings)
        self.greenBtn.setObjectName(u"greenBtn")
        self.greenBtn.setGeometry(QRect(270, 30, 31, 16))
        self.greenBtn.setStyleSheet(u"background-color: green;")
        self.greenBtn.setFlat(False)
        self.blueBtn = QPushButton(self.groupLocatorSettings)
        self.blueBtn.setObjectName(u"blueBtn")
        self.blueBtn.setGeometry(QRect(230, 10, 31, 16))
        self.blueBtn.setStyleSheet(u"background-color: blue;")
        self.blueBtn.setFlat(False)
        self.purpleBtn = QPushButton(self.groupLocatorSettings)
        self.purpleBtn.setObjectName(u"purpleBtn")
        self.purpleBtn.setGeometry(QRect(230, 30, 31, 16))
        self.purpleBtn.setStyleSheet(u"background-color: purple;")
        self.purpleBtn.setFlat(False)
        self.whiteBtn = QPushButton(self.groupLocatorSettings)
        self.whiteBtn.setObjectName(u"whiteBtn")
        self.whiteBtn.setGeometry(QRect(190, 10, 31, 16))
        self.whiteBtn.setStyleSheet(u"background-color: white;")
        self.whiteBtn.setFlat(False)
        self.blackBtn = QPushButton(self.groupLocatorSettings)
        self.blackBtn.setObjectName(u"blackBtn")
        self.blackBtn.setGeometry(QRect(190, 30, 31, 16))
        self.blackBtn.setStyleSheet(u"background-color: black;")
        self.blackBtn.setFlat(False)
        self.ikCtrls = QGroupBox(self.tabAnimation)
        self.ikCtrls.setObjectName(u"ikCtrls")
        self.ikCtrls.setEnabled(True)
        self.ikCtrls.setGeometry(QRect(20, 190, 481, 81))
        self.ikCtrls.setAutoFillBackground(False)
        self.ikCtrls.setFlat(False)
        self.ikCtrls.setCheckable(False)
        self.createIKchainBtn = QPushButton(self.ikCtrls)
        self.createIKchainBtn.setObjectName(u"createIKchainBtn")
        self.createIKchainBtn.setGeometry(QRect(20, 30, 111, 31))
        self.locatorTab = QGroupBox(self.tabAnimation)
        self.locatorTab.setObjectName(u"locatorTab")
        self.locatorTab.setEnabled(True)
        self.locatorTab.setGeometry(QRect(20, 110, 481, 81))
        self.locatorTab.setAutoFillBackground(False)
        self.locatorTab.setFlat(False)
        self.locatorTab.setCheckable(False)
        self.createlocatorBtn = QPushButton(self.locatorTab)
        self.createlocatorBtn.setObjectName(u"createlocatorBtn")
        self.createlocatorBtn.setGeometry(QRect(20, 30, 111, 31))
        self.tabWidget.addTab(self.tabAnimation, "")

        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)


        self.retranslateUi(Form)

        self.tabWidget.setCurrentIndex(2)
        self.orangeBtn.setDefault(False)
        self.redBtn.setDefault(False)
        self.yellowBtn.setDefault(False)
        self.greenBtn.setDefault(False)
        self.blueBtn.setDefault(False)
        self.purpleBtn.setDefault(False)
        self.whiteBtn.setDefault(False)
        self.blackBtn.setDefault(False)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.titleMenuLabel.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:20pt; font-weight:700;\">Mocap Tool Box</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAssetbrowser), QCoreApplication.translate("Form", u"Asset Browser", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRetargeting), QCoreApplication.translate("Form", u"Retargeting", None))
        self.groupTempCtrls.setTitle(QCoreApplication.translate("Form", u"Temp Ctrls", None))
        self.worldSpaceBtn.setText(QCoreApplication.translate("Form", u"World Space", None))
        self.worldSpaceOffsetBtn.setText(QCoreApplication.translate("Form", u"World Space (offset)", None))
        self.bakeSelectedBtn.setText(QCoreApplication.translate("Form", u"BAKE SELECTED", None))
        self.bakeAllBtn.setText(QCoreApplication.translate("Form", u"BAKE ALL", None))
        self.refreshBtn.setText(QCoreApplication.translate("Form", u"refresh", None))
        self.groupLocatorSettings.setTitle(QCoreApplication.translate("Form", u"Locator settings", None))
        self.locSizeMinBtn.setText(QCoreApplication.translate("Form", u"Size -", None))
        self.locSizeMaxBtn.setText(QCoreApplication.translate("Form", u"Size +", None))
        self.orangeBtn.setText("")
        self.redBtn.setText("")
        self.yellowBtn.setText("")
        self.greenBtn.setText("")
        self.blueBtn.setText("")
        self.purpleBtn.setText("")
        self.whiteBtn.setText("")
        self.blackBtn.setText("")
        self.ikCtrls.setTitle(QCoreApplication.translate("Form", u"IK", None))
        self.createIKchainBtn.setText(QCoreApplication.translate("Form", u"Create Ik chain", None))
        self.locatorTab.setTitle(QCoreApplication.translate("Form", u"Locators", None))
        self.createlocatorBtn.setText(QCoreApplication.translate("Form", u"Create Locator", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAnimation), QCoreApplication.translate("Form", u"Animation", None))
    # retranslateUi

